### ISSUE TITLE
tft35 e3 v3.0.1 no printer attatched 

### ISSUE THREAD

**Issue by BCKGRIEVE1** [V1EngineeringInc/MarlinBuilder#133]
ive installed marlin 2.1.1 for skr 1.4 turbo LR Duel and also the updated tft cnc however im now getting no printer attatched ;/

**Comment by V1EngineeringInc** [comment]
Did you trouble shoot the issue in the forums?

Did you flash the matching TFT firmware?

The issue is most likely the mismatch as we use 250000 baud rate and they need to match. Beyond that please troubleshoot in the forums so there are more eyes on this as I do not own the board you are using and can't really help beyond some guesses.

**Comment by BCKGRIEVE1** [comment]
Hey ryan im running in marlin mode now so that will get me by :) thankyou

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
